import type { DealLookups, MarketDeal } from './types';

/**
 * Simulated address-driven lookups. In a real build these come from APIs
 * (Census/ACS income, FEMA flood, crime indices, population projections). Here they are
 * generated deterministically from the location so player-added deals get plausible prefill.
 */
export function simulateLookups(seedKey: string, baseIncome = 55_000): DealLookups {
  let h = 0;
  for (let i = 0; i < seedKey.length; i++) h = (h * 31 + seedKey.charCodeAt(i)) >>> 0;
  const r = (n: number) => ((h = (h * 1103515245 + 12345) >>> 0), (h % 1000) / 1000) * n;
  const floodZones = ['Zone X (minimal risk)', 'Zone X (minimal risk)', 'Zone AE (100-yr)', 'Zone X (shaded)'];
  return {
    medianHouseholdIncome: Math.round((baseIncome + r(35_000)) / 500) * 500,
    floodZone: floodZones[Math.floor(r(floodZones.length))],
    crimeIndex: Math.round(20 + r(55)),
    populationTrendPct: +(((r(40) - 8) / 10)).toFixed(1), // ~ −0.8% .. +3.2%
    rentGrowthYoYPct: +(((r(60)) / 10) - 1).toFixed(1), // ~ −1% .. +5%
  };
}

/** Seeded synthetic multifamily deals (no scraping). Span great → over-priced for teaching value. */
export const SEED_DEALS: MarketDeal[] = [
  {
    id: 'villas-del-norte',
    name: 'Villas del Norte',
    address: '4400 Western Center Blvd',
    city: 'Fort Worth',
    state: 'TX',
    msa: 'Dallas–Fort Worth, TX',
    assetClass: 'multifamily',
    vintage: 1998,
    unitCount: 184,
    rentableSqft: 162_000,
    askPrice: 19_500_000,
    avgInPlaceRent: 1180,
    avgMarketRent: 1320,
    otherIncomePerUnitPerYr: 720,
    expensePerUnit: 5200,
    currentVacancy: 0.11,
    stabilizedVacancy: 0.07,
    walkInCapRate: 0.062,
    stabilizedCapRate: 0.068,
    propertyRating: 3,
    locationRating: 4,
    lookups: { medianHouseholdIncome: 58_000, floodZone: 'Zone X (minimal risk)', crimeIndex: 38, populationTrendPct: 1.8, rentGrowthYoYPct: 3.1 },
    broker: 'Marcus & Millichap — J. Alvarez',
    source: 'Broker email blast',
    blurb:
      'Value-add 1998 vintage with a loss-to-lease story; in-place rents ~$140 under market. Light interior renovation underway on turns.',
  },
  {
    id: 'oakwood-crossing',
    name: 'Oakwood Crossing',
    address: '910 Wells Branch Pkwy',
    city: 'Austin',
    state: 'TX',
    msa: 'Austin–Round Rock, TX',
    assetClass: 'multifamily',
    vintage: 2006,
    unitCount: 240,
    rentableSqft: 228_000,
    askPrice: 41_000_000,
    avgInPlaceRent: 1490,
    avgMarketRent: 1560,
    otherIncomePerUnitPerYr: 840,
    expensePerUnit: 6100,
    currentVacancy: 0.09,
    stabilizedVacancy: 0.06,
    walkInCapRate: 0.05,
    stabilizedCapRate: 0.054,
    propertyRating: 4,
    locationRating: 5,
    lookups: { medianHouseholdIncome: 79_000, floodZone: 'Zone X (minimal risk)', crimeIndex: 27, populationTrendPct: 2.6, rentGrowthYoYPct: 2.2 },
    broker: 'CBRE — Priya Nair',
    source: 'Listed on Crexi',
    blurb:
      'Core-plus Austin asset, well located but priced to perfection at a sub-5.5% stabilized cap. Thin margin for error.',
  },
  {
    id: 'magnolia-trace',
    name: 'Magnolia Trace',
    address: '7322 Antoine Dr',
    city: 'Houston',
    state: 'TX',
    msa: 'Houston–The Woodlands, TX',
    assetClass: 'multifamily',
    vintage: 1984,
    unitCount: 312,
    rentableSqft: 252_000,
    askPrice: 22_800_000,
    avgInPlaceRent: 990,
    avgMarketRent: 1180,
    otherIncomePerUnitPerYr: 600,
    expensePerUnit: 4900,
    currentVacancy: 0.14,
    stabilizedVacancy: 0.08,
    walkInCapRate: 0.066,
    stabilizedCapRate: 0.075,
    propertyRating: 2,
    locationRating: 3,
    lookups: { medianHouseholdIncome: 49_000, floodZone: 'Zone AE (100-yr)', crimeIndex: 61, populationTrendPct: 1.1, rentGrowthYoYPct: 1.6 },
    broker: 'Berkadia — T. Okafor',
    source: 'Pocket listing',
    blurb:
      'Heavy value-add 1980s deal with real upside ($190 loss-to-lease) but operational hair: high vacancy, deferred maintenance, choppy collections.',
  },
  {
    id: 'cedar-park-flats',
    name: 'Cedar Park Flats',
    address: '1500 E Whitestone Blvd',
    city: 'Cedar Park',
    state: 'TX',
    msa: 'Austin–Round Rock, TX',
    assetClass: 'multifamily',
    vintage: 2015,
    unitCount: 156,
    rentableSqft: 148_200,
    askPrice: 28_500_000,
    avgInPlaceRent: 1620,
    avgMarketRent: 1690,
    otherIncomePerUnitPerYr: 900,
    expensePerUnit: 6300,
    currentVacancy: 0.07,
    stabilizedVacancy: 0.05,
    walkInCapRate: 0.052,
    stabilizedCapRate: 0.057,
    propertyRating: 5,
    locationRating: 5,
    lookups: { medianHouseholdIncome: 92_000, floodZone: 'Zone X (minimal risk)', crimeIndex: 19, populationTrendPct: 3.0, rentGrowthYoYPct: 2.8 },
    broker: 'JLL — M. Carter',
    source: 'Listed on LoopNet',
    blurb:
      'Newer, stabilized suburban asset in a strong school district. Low risk, low yield — a "sleep at night" deal that barely pencils on price.',
  },
  {
    id: 'san-jacinto-square',
    name: 'San Jacinto Square',
    address: '2201 N Zarzamora St',
    city: 'San Antonio',
    state: 'TX',
    msa: 'San Antonio–New Braunfels, TX',
    assetClass: 'multifamily',
    vintage: 1991,
    unitCount: 208,
    rentableSqft: 174_700,
    askPrice: 17_600_000,
    avgInPlaceRent: 1040,
    avgMarketRent: 1210,
    otherIncomePerUnitPerYr: 660,
    expensePerUnit: 5000,
    currentVacancy: 0.12,
    stabilizedVacancy: 0.07,
    walkInCapRate: 0.064,
    stabilizedCapRate: 0.072,
    propertyRating: 3,
    locationRating: 3,
    lookups: { medianHouseholdIncome: 52_000, floodZone: 'Zone X (minimal risk)', crimeIndex: 48, populationTrendPct: 1.4, rentGrowthYoYPct: 2.0 },
    broker: 'Newmark — L. Brooks',
    source: 'Broker call',
    blurb:
      'Solid blue-collar San Antonio value-add. Reasonable basis, achievable rent bumps, manageable business plan. A bread-and-butter deal.',
  },
  {
    id: 'riverbend-park',
    name: 'Riverbend Park',
    address: '5050 Buffalo Speedway',
    city: 'Houston',
    state: 'TX',
    msa: 'Houston–The Woodlands, TX',
    assetClass: 'multifamily',
    vintage: 1972,
    unitCount: 96,
    rentableSqft: 72_000,
    askPrice: 9_800_000,
    avgInPlaceRent: 950,
    avgMarketRent: 1050,
    otherIncomePerUnitPerYr: 540,
    expensePerUnit: 5400,
    currentVacancy: 0.16,
    stabilizedVacancy: 0.1,
    walkInCapRate: 0.058,
    stabilizedCapRate: 0.064,
    propertyRating: 2,
    locationRating: 2,
    lookups: { medianHouseholdIncome: 44_000, floodZone: 'Zone AE (100-yr)', crimeIndex: 72, populationTrendPct: -0.4, rentGrowthYoYPct: 0.9 },
    broker: 'Owner direct',
    source: 'Direct-to-seller (cold outreach)',
    blurb:
      'Tired 1970s product below the buy-box vintage line. Seller is firm on an aggressive price; numbers say you would be paying over value.',
  },
  {
    id: 'desert-vista',
    name: 'Desert Vista Apartments',
    address: '3030 E Thomas Rd',
    city: 'Phoenix',
    state: 'AZ',
    msa: 'Phoenix–Mesa, AZ',
    assetClass: 'multifamily',
    vintage: 2001,
    unitCount: 220,
    rentableSqft: 198_000,
    askPrice: 36_000_000,
    avgInPlaceRent: 1380,
    avgMarketRent: 1500,
    otherIncomePerUnitPerYr: 780,
    expensePerUnit: 5800,
    currentVacancy: 0.1,
    stabilizedVacancy: 0.06,
    walkInCapRate: 0.054,
    stabilizedCapRate: 0.06,
    propertyRating: 4,
    locationRating: 4,
    lookups: { medianHouseholdIncome: 71_000, floodZone: 'Zone X (minimal risk)', crimeIndex: 35, populationTrendPct: 2.3, rentGrowthYoYPct: 1.4 },
    broker: 'Institutional Property Advisors',
    source: 'Listed on Crexi',
    blurb:
      'Decent Phoenix value-add — but out of the default TX buy box. A test of discipline: good deal, wrong market for your thesis?',
  },
  {
    id: 'pecan-grove',
    name: 'Pecan Grove Townhomes',
    address: '880 W Pleasant Run Rd',
    city: 'Lancaster',
    state: 'TX',
    msa: 'Dallas–Fort Worth, TX',
    assetClass: 'multifamily',
    vintage: 2003,
    unitCount: 128,
    rentableSqft: 140_800,
    askPrice: 15_900_000,
    avgInPlaceRent: 1280,
    avgMarketRent: 1450,
    otherIncomePerUnitPerYr: 960,
    expensePerUnit: 5300,
    currentVacancy: 0.1,
    stabilizedVacancy: 0.06,
    walkInCapRate: 0.063,
    stabilizedCapRate: 0.071,
    propertyRating: 4,
    locationRating: 4,
    lookups: { medianHouseholdIncome: 61_000, floodZone: 'Zone X (minimal risk)', crimeIndex: 41, populationTrendPct: 2.0, rentGrowthYoYPct: 3.4 },
    broker: 'Marcus & Millichap — D. Reyes',
    source: 'Broker email blast',
    blurb:
      'Townhome-style product (sticky tenants, low turnover) with strong other-income upside via a RUBS roll-out. Clean value-add with a wide margin.',
  },
];
